branches:
  only: 
    - master
matrix:
  include:
    - stage: "lint"
      language: node_js
      os: linux
      node_js: "8"
      script: 
        - cd src && npm run ci.tslint
        - cd ../demo && npm run ci.tslint
        - cd ../demo-angular && npm run ci.tslint

    - stage: "build demos"
      os: linux
      env: 
        - BuildAndroid="28"
      language: android
      jdk: oraclejdk8
      before_install: nvm install 8.11.4
      script: 
        - cd src && npm run build
        - cd ../demo && tns build android
        - cd ../demo-angular && tns build android

    - os: osx
      env: 
        - BuildiOS="12.0"
        - Xcode="10.0"
      osx_image: xcode10.0
      language: node_js 
      node_js: "8"
      jdk: oraclejdk8
      script: 
        - cd src && npm run build
        - cd ../demo && tns build ios
        - cd ../demo-angular && tns build ios

    - stage: "build demos with webpack"
      os: linux
      language: android
      env:
        - Webpack="Android"
      jdk: oraclejdk8
      before_install: nvm install 8.11.4
      script: 
        - cd src && npm run build
        - cd ../demo && tns build android --bundle --env.uglify --env.snapshot --env.aot
        - cd ../demo-angular && tns build android --bundle --env.uglify --env.snapshot --env.aot
        - cd ../demo-vue && tns build android --bundle --env.uglify --env.snapshot --env.aot
      
    - os: osx
      env:
        - Webpack="iOS"
      osx_image: xcode10.0
      language: node_js 
      node_js: "8"
      jdk: oraclejdk8
      script: 
        - cd src && npm run build
        - cd ../demo && tns build ios --bundle --env.uglify --env.aot
        - cd ../demo-angular && tns build ios --bundle --env.uglify --env.aot
        - cd ../demo-vue && tns build ios --bundle --env.uglify --env.aot

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - extra-android-m2repository

before_install:
    - sudo pip install --upgrade pip
    - sudo pip install six

install:
    - echo no | npm install -g nativescript
    - tns usage-reporting disable
    - tns error-reporting disable
